# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

abstract_target 'ios-interview' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-interview
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'CocoaLumberjack/Swift'
  pod 'TinyConstraints'
  pod 'Reusable'
  pod 'CFATheme', :git => 'https://github.com/mgray88/CFATheme.git', :modular_headers => true
  pod 'MBProgressHUD'

  target 'ios-interview-objc'
  target 'ios-interview-swift'

end

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.2'
    end
  end
end
